rtmp:
  archive_path:     ../dev/local/archive
  archive_raw_path: ../dev/local/archive_raw
  recordings_path:  ../dev/local/recordings
faye:
  server: http://localhost:9292/faye
  secret_token: 7650981269q2871928631823791287e
limit:
  text: 2300
  string: 140
errbit:
  enabled: false
  api_key: 'this will be set on the stages in app/shared/config/settings.local.yml'
  environment: 'development'
# set in local!
site_root: 'http://localhost:3000'

fog:
  storage:
    provider: AWS
    region: eu-central-1
    aws_access_key_id: AKIAI7HSKHN3FBT2KAZQ
    aws_secret_access_key: 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

storage:
  backup_recordings: vr-euc1-dev-backup-recordings@eu-central-1
