rtmp:
  archive_path:     ../dev/local/archive
  archive_raw_path: ../dev/local/archive_raw
  recordings_path:  ../dev/local/recordings
faye:
  server: http://localhost:9292/faye
  secret_token: 7650981269q2871928631823791287e
limit:
  text: 2300
  string: 140
errbit:
  enabled: false
  api_key: 'this will be set on the stages in app/shared/config/settings.local.yml'
  environment: 'development'
root_url: 'http://localhost:3000'
